from enum import Enum

class PrivatizationStatus(Enum):
    SUCCESS = "SUCCESS"
    INVALID_FORMAT = "INVALID_FORMAT"
    FAILURE_INVALID_COOKIE = "FAILURE_INVALID_COOKIE"
    FAILURE_LOGIN_REDIRECT = "FAILURE_LOGIN_REDIRECT"
    FAILURE_API_ERROR = "FAILURE_API_ERROR"
    FAILURE_NETWORK = "FAILURE_NETWORK"
    FAILURE_OPERATIONAL = "FAILURE_OPERATIONAL" 